### PR TITLE
resilience against rounding error in timestamp in test_caching fixture

### LINKED ISSUE #1423: Caching test for bearer token authentication intermittently fails
The test:
`normandy.base.tests.api.test_authentication.TestBearerTokenAuthentication.test_caching`

We currently use `sleep` to add a delay that is 1 second longer than the time in which the cache should expire but this appears to intermittently cause issues and can hopefully be done in a better way.

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #1423 

Hopefully my comment is clear enough. A way to "visualize" it is to create [a script like this](https://gist.github.com/peterbe/699e6826a82717e896a8ddb9b0a53fde).

### CODE REVIEW

**Comment by peterbe** [comment]
I've actually never used it but I've reviewed some code that uses [freezegun](https://github.com/spulec/freezegun). We used it in socorro to mock dates but I don't know if it can be used in this case. Would be cool. It might resolve the icky problem that a single unit tests 2+ seconds to run when it could be done in 0.02 seconds in theory.

**Comment by peterbe** [comment]
Perhaps a follow-up issue to use freezegun. Do we have a lot of other unit tests that could benefit from it?

**Comment by peterbe** [comment]
ping @rehandalal

**Comment by peterbe** [comment]
Judging by ripgrep, we only have 1 single instance of using `time.sleep`. Just park this idea of using freezegun somewhere in the back.

**Comment by rehandalal** [comment]
> Just park this idea of using freezegun somewhere in the back.

Yeah it's not high priority but getting the extra seconds back would be nice.

**Pull request merged**
