### PR TITLE
Check cert root and subject in heartbeat

### PR DESCRIPTION
**Pull request by mythmon**
This would have caught some of our recent signature problems.

@g-k can you take a look at how I validated the certificates here?

### CODE REVIEW

**Comment by mythmon** [comment]
@g-k in that case, can you share the certificate that we were using that caused the problem? I'd like to understand what went wrong, and what Firefox is actually checking that wasn't right.

**Comment by g-k** [comment]
@mythmon of course! https://gist.github.com/g-k/520ab1300267afd645cc67a179a8a056

**Comment by mythmon** [comment]
@g-k Luckily, Gist's have raw URLs :smile:. I was able to use that to test it.

So the issue here is that the issuer and the subject were the same? That sounds like it might be more than what I want to check without a full fledged x509 validator. That sounds a bit out of scope, even more so than this PR already is.

**Comment by g-k** [comment]
@mythmon Yeah, agreed it's probably more than you want to check. We're planning to fully automate the contentsignature rotation soon, so that should rule out the self-signed cert errors (and we'll check for those from the autograph monitor).

**Comment by mythmon** [comment]
bors r= @rehandalal, @g-k

**Pull request merged**
