### PR TITLE
Upgrade Django to v2.1.7

### PR DESCRIPTION
**Pull request by rehandalal**
Blocked by #1752.

r?

### CODE REVIEW

**Comment by rehandalal** [comment]
Hmm... Looks like some autograph issues...

**Comment by mythmon** [comment]
I think we don't usually use Autograph itself during tests, but instead are doing mocked signing by making the "signature" actually a normal hash of the data. I don't know why that would break in the update though. I skimmed through the release note and didn't find anything that seemed relevant.

**Comment by peterbe** [comment]
@rehandalal can you fix the conflicts and then I can review this.

**Comment by peterbe** [comment]
"review" :)

**Comment by mythmon** [comment]
@rehandalal can you check what you get at `/api/docs/`? It isn't working for me, due to not being able to find jquery, but I also have some other weird stuff happening, so I'm not sure.

Besides that, everything I checked seems to work fine.

**Comment by rehandalal** [comment]
image

Appears to be an inline script CSP issue.

**Comment by rehandalal** [comment]
I hit refresh and it looked okay though...

image

Still seeing the CSP issues in the console however.

**Comment by mythmon** [comment]
The CSP stuff is probably from #1765. You're getting way farther than I am, so I think this is ok.

**Pull request merged**
