### PR TITLE
Changes needed for bors

### PR DESCRIPTION
**Pull request by mythmon**
If this works, we should be able to start using bors with this PR.

To test this, after you're happy with this, say "bors r+" on it's own line. For more info, see [the bors command docs](https://bors.tech/documentation/). You should be able to include the command in a GitHub review comment, if that's your thing.

### CODE REVIEW

**Comment by rehandalal** [comment]
seems fine to me...

bors r+

**Comment by mythmon** [comment]
As an experiment, do I have permission here?

bors delegate=rehandalal

**Comment by notriddle** [comment]
@moz-hwine is the only user with permission to review things on this repo (because hwine added the app itself).

I guess that's some sort of "org user" with sole admin permissions for all repos? Because hwine's going to need to add the other reviewers.

**Comment by mythmon** [comment]
@notriddle I think you're spot on. I posted about one long term solution to this [in the forum](https://forum.bors.tech/t/automatically-giving-access-to-repo-admins/85/1). I've been talking with @moz-hwine on Bugzilla for a bit to try and get this sorted.

**Comment by mythmon** [comment]
ok! Once more, with feeling!

bors r+

**Pull request merged**
