### PR TITLE
Update action arguments schemas package to v0.7.0 

### PR DESCRIPTION
**Pull request by rehandalal**
r?

### CODE REVIEW

**Comment by peterbe** [comment]
Whatever happened to 0.4.0, 0.5.0, 0.6.0??

**Comment by mythmon** [comment]
* v0.4.0 Was making add-on studies a action.
* v0.5.0 Was a simple change to make the schema more correct, but didn't have consequences for the server.
* v0.6.0 Was implementing heartbeat as a local action.
* v0.7.0 Was a retroactive bump for preference-experiments as a local action.

None of these *require* updating the server, but bringing in the new version is a good idea. I think there is a small chance that this has issues when we deploy, but we will catch it in stage. @peterbe do you remember what we did for conflicting schemas between this package and the schemas in the git repo?

**Comment by mythmon** [comment]
Since @peterbe approved this already, I'm going to assume it will be fine, an dif not we'll catch it in stage.

bors r= @peterbe

**Comment by peterbe** [comment]
> do you remember what we did for conflicting schemas between this package and the schemas in the git repo?

Quick answer; no. :)

Long answer; the code comments here: https://github.com/mozilla/normandy/blob/844b048d2be15f0bce2b8e3705d17ae3a21fb315/normandy/recipes/management/commands/update_actions.py#L78-L95 speak for themselves pretty well. Essentially, a warning is displayed on stdout. 

Perhaps that's not what you're referring to but it's a try.

**Pull request merged**
