### PR TITLE
Store test artifacts for CI processing

### PR DESCRIPTION
**Pull request by mythmon**
@relud r?

### CODE REVIEW

**Comment by relud** [comment]
you might need -u root

**Comment by mythmon** [comment]
Wait, that's an option? That would have saved me a lot of debugging...

**Comment by mythmon** [comment]
Though, on the other hand running the tests as root might hide errors that we will hit when the servers run as not-root. I'm going to try and work around it for now.

**Comment by relud** [comment]
you could work around it by creating the reports dir and chowning it as app in the dockerfile before the requirements.txt is copied in.

**Comment by mythmon** [comment]
Sort of, except the directory already exists, and is created by CircleCI. I chowned it as a part of the CI set up, and it worked.

**Comment by relud** [comment]
ah, okay, cool

**Comment by mythmon** [comment]
This worked and we got data in the last test run. Merging.

**Pull request merged**
