### PR TITLE
Use licence to download the GeoLite2 Country DB (fixes #2069)

### LINKED ISSUE #2069: GeoLite2 database is no longer available publicly
An account is required on the maxmind.com website, and an API required for download.

Shall we do that? Shall we remove the GeoIP parts of Normandy instead?

### PR DESCRIPTION
**Pull request by leplatrem**
Fixes #2069 

An account should be created on maxmind.com and the licence key be put in `MAXMIND_LICENCE_KEY` env var on CircleCI.

@sciurus Do we want a BZ ticket for that?

### CODE REVIEW

**Comment by mythmon** [comment]
@tiftran Does the Docker workflow you set up use this script as well?

**Comment by tiftran** [comment]
@mythmon  yes, docker workflow uses download_geolite2.sh

**Comment by mythmon** [comment]
We'll need to make sure that the Docker workflow is updated too, either to not use GeoIP, or to guide the user into configuring authentication for this.

If we can get CI working before all of the above nice-to-haves, I'm fine landing this without updating docs/Docker to unblock things.

**Comment by tiftran** [comment]
@mythmon  sounds good, I'll create a separate issue for updating the docker workflow?

**Comment by mythmon** [comment]
Sure, that sounds like a good plan. They are pretty independent.

**Comment by leplatrem** [comment]
Since in prod, there is already a different workflow, with auth and the update tool, I don't think it makes sense to modify the dev/CI script this way.

**Pull request closed without merging**
