### PR TITLE
New revisions and simple filters

### PR DESCRIPTION
**Pull request by rehandalal**
This is just the code in the [peer-signing](https://github.com/mozilla/normandy/tree/peer-signing) feature branch rebased against master.

r?

### CODE REVIEW

**Comment by mythmon** [comment]
#430 has merged. Rebasing this on master will fix the build.

**Comment by rehandalal** [comment]
re-rebased

**Comment by mythmon** [comment]
This error came out of CI:

```
Unknown command: 'update_product_details
```

**Comment by rehandalal** [comment]
@chartjes this is ready for review. just a reminder, this is code that was already reviewed and merged to a feature branch. we are just merging the feature branch into master.

**Comment by mythmon** [comment]
@karlht Can you review this PR as a representative for QA? We normally have Chris Hartjes review all of our PRs on the project for good test coverage and QA usability, but he is at a conference this week. This PR is merging a long-running feature branch that we've been working on into our master branch so we can deploy it. All the code on the branch has been reviewed by both dev and QA in other PRs, with the exception of the last 3 commits.

This commit is blocking several other things we'd like to move forward with, otherwise we'd wait until Chris was back.

**Comment by mythmon** [comment]
Thanks for going through this. It is definitely a weird situation. We haven't done one of these types of merges yet, so we haven't quite figured out the way we want to do things yet.

For reference, the PRs where the original review was done were #410 and #423, and the original branch was [peer-signing](https://github.com/mozilla/normandy/tree/peer-signing). Because of our switch to a monorepo, it is a bit hard to diff the original branch against this one, but scanning through the list of commits between the two is pretty easy.

**Pull request merged**
