### PR TITLE
#395 Active Filters

### PR DESCRIPTION
**Pull request by andymikulski**
Related to #395 

- Adds filter reducer, actions, selectors
- Adds 'active filter' section (ActiveFilters component)
- Adds RecipeCombobox, RecipeCount, ActiveFilters, GroupMenu components
- Adds filter API calls (_not_ the actual API responses, though)
- Adds recipe list caching (user adds filter -> if that filter was loaded already, that list is shown -> api call is still made -> list is updated with fresh server results)
- Adds filter tests
- Adds a handful of missing util tests

NOTE: I'd like @mythmon or @rehandalal to check out the tests, specifically the API tests (the `LOAD_FILTERS` stuff in `test_filterActions`) - I had copied other API tests as an example, but I'm not totally convinced it's as thorough as it could/should be. After that, I'll request a QA review.

### CODE REVIEW

**Comment by andymikulski** [comment]
I'd like to refactor some of `client/control/actions/ControlActions` before becomes a bit monolothic, but that may turn into another PR. Either way, at this point, this PR is ready for review.

**Comment by andymikulski** [comment]
To test the filters locally without an endpoint, use this gist to replace the `loadFilters` action - https://gist.github.com/andymikulski/8536d1218343446262cdade1790ebc59

**Comment by mythmon** [comment]
This is a pretty large patch (necessarily so, I think). I didn't look through all of it, but from what I've read, I'm concerned about landing this on master without the APIs to match. I think that it will be a better idea to create a feature branch, and land this PR on it, as well as the APIs for filter options and recipe filtering.

The main concern here is that this feature is not ready for production (since it relies on APIs that are not written), and the goal is that master is always ready for production (at least in theory). As naive an idea as that is, I think it is still a good goal to strive for.

Can we recreate this PR to merge into a feature branch instead of master? Or do you think that's a crazy idea?

**Comment by andymikulski** [comment]
Yep, that makes sense, I'll go ahead and close this PR etc.

**Comment by andymikulski** [comment]
New PR onto the `316-simplified-filters` feature branch is located at #405

**Pull request closed without merging**
