### PR TITLE
Disable newrelic browser monitoring

### PR DESCRIPTION
**Pull request by relud**
needs testing to confirm that it works

### CODE REVIEW

**Comment by mythmon** [comment]
I have no way of testing that this has the desired affect, but it does seem like it should, and this shouldn't break anything. What can we do to test this?

**Comment by relud** [comment]
maybe I can build a docker container and push it to docker hub, and I can run it on stage, and then curl a page and look for the script tag we are supposed to be disabling ?

**Comment by mythmon** [comment]
That would work.

**Comment by relud** [comment]
okay, confirmed, it does what we expect on stage, and it doesn't break newrelic either

**Comment by mythmon** [comment]
Cool, thanks for testing it.

**Pull request merged**
