### PR TITLE
Add a PresetFilter filter object for Pocket

### PR DESCRIPTION
**Pull request by mythmon**
I was a bit sneaky here and also included AND and OR filters, since they were
helpful.

### CODE REVIEW

**Comment by mythmon** [comment]
Filter objects build docs from their docstrings almost automatically, though I see that I should tweak the preset one. I'll see if I can get a way to pull the preset options into the docs as well without having to just duplicate them.

image

image

**Comment by rehandalal** [comment]
TIL: ^

**Comment by mythmon** [comment]
image

bors r= @rehandalal

**Comment by mythmon** [comment]
bors cancel

**Comment by mythmon** [comment]
bors r= @rehandalal

**Comment by mythmon** [comment]
bors retry

**Pull request merged**
