### PR TITLE
Django 1.11.11

### PR DESCRIPTION
**Pull request by peterbe**
I don't know how else to test this. I started the server and clicked around a bit but I'm still not sure I know what I'm doing. At least the tests pass without and deprecation warnings *we* can immediately do something about:

```
▶ PYTHONWARNINGS=d pytest
/Users/peterbe/virtualenvs/recipe-server/bin/../lib/python3.6/site.py:165: DeprecationWarning: 'U' mode is deprecated
  f = open(fullname, "rU")
/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/importlib/_bootstrap_external.py:426: ImportWarning: Not importing directory /Users/peterbe/virtualenvs/recipe-server/lib/python3.6/site-packages/sphinxcontrib: missing __init__
  _warnings.warn(msg.format(portions[0]), ImportWarning)
/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/importlib/_bootstrap_external.py:426: ImportWarning: Not importing directory /Users/peterbe/virtualenvs/recipe-server/lib/python3.6/site-packages/backports: missing __init__
  _warnings.warn(msg.format(portions[0]), ImportWarning)
/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:7: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/site-packages/pytest_testrail/conftest.py:3: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .plugin import TestRailPlugin
/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/site-packages/pytest_testrail/conftest.py:4: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .testrail_api import APIClient
/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/site-packages/pytest_django/plugin.py:17: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .django_compat import is_django_unittest
/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/site-packages/pytest_django/plugin.py:18: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .fixtures import (_django_db_setup, _live_server_helper, admin_client,
/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/site-packages/pytest_django/fixtures.py:10: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from . import live_server_helper
/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/site-packages/pytest_django/live_server_helper.py:3: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .lazy_django import get_django_version
/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/site-packages/pytest_django/fixtures.py:11: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .db_reuse import (monkey_patch_creation_for_db_reuse,
/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/site-packages/pytest_django/fixtures.py:13: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .django_compat import is_django_unittest
/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/site-packages/pytest_django/fixtures.py:14: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .lazy_django import get_django_version, skip_if_no_django
/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/site-packages/pytest_django/plugin.py:22: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .lazy_django import django_settings_is_configured, skip_if_no_django
/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/site-packages/pytest_django/plugin.py:50: DeprecationWarning: type argument to addoption() is a string 'string'. For parsearg this should be a type. (options: ('--ds',))
  help='Set DJANGO_SETTINGS_MODULE.')
/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/site-packages/pytest_django/plugin.py:53: DeprecationWarning: type argument to addoption() is a string 'string'. For parsearg this should be a type. (options: ('--dc',))
  help='Set DJANGO_CONFIGURATION.')
================================================================================================ test session starts ================================================================================================
platform darwin -- Python 3.6.4, pytest-3.0.2, py-1.4.31, pluggy-0.3.1
django settings: normandy.settings (from ini file)
rootdir: /Users/peterbe/dev/MOZILLA/NORMANDY/normandy/recipe-server, inifile: pytest.ini
plugins: testrail-0.0.11, mock-0.11.0, django-2.9.1
collected 352 items

normandy/base/tests/test_api.py ....x..............
normandy/base/tests/test_auth_backends.py ...
normandy/base/tests/test_decorators.py ...
normandy/base/tests/test_middleware.py ....
normandy/base/tests/test_renderers.py .
normandy/base/tests/test_storage.py .....
normandy/base/tests/test_templatetags.py ..
normandy/base/tests/test_urls.py .
normandy/base/tests/test_utils.py ........
normandy/base/tests/test_views.py ..
normandy/control/tests/test_templatetags.py ..
normandy/health/tests/test_api.py ........
normandy/recipes/tests/test_admin.py ..
normandy/recipes/tests/test_checks.py ....
normandy/recipes/tests/test_commands.py ....................
normandy/recipes/tests/test_factories.py ...
normandy/recipes/tests/test_geolocation.py ....
normandy/recipes/tests/test_models.py ................................................
normandy/recipes/tests/test_signing.py ......................
normandy/recipes/tests/test_storage.py .
normandy/recipes/tests/test_utils.py .......
normandy/recipes/tests/test_validators.py .
normandy/recipes/tests/api/v1/test_api.py .........................................................................
normandy/recipes/tests/api/v1/test_serializers.py ..........
normandy/recipes/tests/api/v2/test_api.py ..................................................................
normandy/recipes/tests/api/v2/test_serializers.py ......
normandy/recipes/tests/api/v2/test_shield_identicon.py ...
normandy/selfrepair/tests/test_views.py ....
normandy/studies/tests/test_models.py .
normandy/studies/tests/api/v2/test_api.py ..................
normandy/studies/tests/api/v2/test_serializers.py .

====================================================================================== 351 passed, 1 xfailed in 30.48 seconds =======================================================================================
```

### CODE REVIEW

**Comment by peterbe** [comment]
Before I forget, I suspect our current `webpack_loader` will not fly when we upgrade to Django 2

```
▶ PYTHONWARNINGS=d ./bin/runsslserver.sh
/Users/peterbe/virtualenvs/recipe-server/bin/../lib/python3.6/site.py:165: DeprecationWarning: 'U' mode is deprecated
  f = open(fullname, "rU")
/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/site-packages/configurations/importer.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/importlib/_bootstrap_external.py:426: ImportWarning: Not importing directory /Users/peterbe/virtualenvs/recipe-server/lib/python3.6/site-packages/sphinxcontrib: missing __init__
  _warnings.warn(msg.format(portions[0]), ImportWarning)
/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/importlib/_bootstrap_external.py:426: ImportWarning: Not importing directory /Users/peterbe/virtualenvs/recipe-server/lib/python3.6/site-packages/backports: missing __init__
  _warnings.warn(msg.format(portions[0]), ImportWarning)
/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/site-packages/jinja2/filters.py:24: DeprecationWarning: Flags not at the start of the expression '\\w+(?u)'
  _word_re = re.compile(r'\w+(?u)')
/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/importlib/_bootstrap.py:971: ResourceWarning: unclosed file <_io.TextIOWrapper name='/Users/peterbe/dev/MOZILLA/NORMANDY/normandy/recipe-server/normandy/settings.py' mode='r' encoding='utf-8'>
  return _find_and_load_unlocked(name, import_)
/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/site-packages/pygments/util.py:27: DeprecationWarning: Flags not at the start of the expression '<(.+?)(\\s.*?)?>.*?</' (truncated)
  tag_re = re.compile(r'<(.+?)(\s.*?)?>.*?</.+?>(?uism)')
/Users/peterbe/virtualenvs/recipe-server/bin/../lib/python3.6/site.py:165: DeprecationWarning: 'U' mode is deprecated
  f = open(fullname, "rU")
/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/site-packages/configurations/importer.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/importlib/_bootstrap_external.py:426: ImportWarning: Not importing directory /Users/peterbe/virtualenvs/recipe-server/lib/python3.6/site-packages/sphinxcontrib: missing __init__
  _warnings.warn(msg.format(portions[0]), ImportWarning)
/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/importlib/_bootstrap_external.py:426: ImportWarning: Not importing directory /Users/peterbe/virtualenvs/recipe-server/lib/python3.6/site-packages/backports: missing __init__
  _warnings.warn(msg.format(portions[0]), ImportWarning)
/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/site-packages/jinja2/filters.py:24: DeprecationWarning: Flags not at the start of the expression '\\w+(?u)'
  _word_re = re.compile(r'\w+(?u)')
/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/importlib/_bootstrap.py:971: ResourceWarning: unclosed file <_io.TextIOWrapper name='/Users/peterbe/dev/MOZILLA/NORMANDY/normandy/recipe-server/normandy/settings.py' mode='r' encoding='utf-8'>
  return _find_and_load_unlocked(name, import_)
/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/site-packages/pygments/util.py:27: DeprecationWarning: Flags not at the start of the expression '<(.+?)(\\s.*?)?>.*?</' (truncated)
  tag_re = re.compile(r'<(.+?)(\s.*?)?>.*?</.+?>(?uism)')
Validating models...

/Users/peterbe/virtualenvs/recipe-server/lib/python3.6/site-packages/webpack_loader/templatetags/webpack_loader.py:54: RemovedInDjango20Warning: assignment_tag() is deprecated. Use simple_tag() instead
  def get_files(bundle_name, extension=None, config='DEFAULT'):
System check identified no issues (0 silenced).
March 07, 2018 - 20:56:18
Django version 1.11.11, using settings 'normandy.settings'
Starting development server at https://127.0.0.1:8000/
Using SSL certificate: /Users/peterbe/dev/MOZILLA/NORMANDY/normandy/recipe-server/etc/ssl/normandy_dev.cert
Using SSL key: /Users/peterbe/dev/MOZILLA/NORMANDY/normandy/recipe-server/etc/ssl/normandy_dev.key
Quit the server with CONTROL-C.
```

**Comment by mythmon** [comment]
> Before I forget, I suspect our current webpack_loader will not fly when we upgrade to Django 2

Luckily, by the time we switch to Django 2, we won't need to have any webpack loaders or any client JS at all. So that's great.

If all the tests and CI pass, and there aren't explosive errors from a basic click through of the site, I'm happy to approve this. We have pretty good automated tests and sort of ok automatic verification of, and the UI is almost entirely JS anyways.

That being said, there was a problem in the dependencies step of the CI. It is related to the mock-server, which is going away. It may represent a problem in the update though. Can you look into it?

```
Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 206, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/app/normandy/recipes/management/commands/initial_data.py", line 2, in <module>
    from django_countries import countries
  File "/usr/local/lib/python3.6/site-packages/django_countries/__init__.py", line 5, in <module>
    from django_countries.conf import settings
  File "/usr/local/lib/python3.6/site-packages/django_countries/conf.py", line 4, in <module>
    class AppSettings(django.conf.BaseSettings):

AttributeError: module 'django.conf' has no attribute 'BaseSettings'
```

**Comment by peterbe** [comment]
Yay!

**Comment by mythmon** [comment]
I guess I should be more careful relying on the the test suite.

Running this locally and then visiting https://localhost:8000/api/v1/recipe/, I get the error below. Looking into this some more, DRF doesn't enable HTML output in tests by default, [and the instructions to enable it](http://www.django-rest-framework.org/api-guide/testing/#setting-the-available-formats) didn't work for me. In other words, I can't reproduce this problem in a test, which makes me very sad.

```
Traceback:

File "/home/mythmon/src/normandy/recipe-server/.direnv/python-3.6.4/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/home/mythmon/src/normandy/recipe-server/.direnv/python-3.6.4/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  217.                 response = self.process_exception_by_middleware(e, request)

File "/home/mythmon/src/normandy/recipe-server/.direnv/python-3.6.4/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  215.                 response = response.render()

File "/home/mythmon/src/normandy/recipe-server/.direnv/python-3.6.4/lib/python3.6/site-packages/django/template/response.py" in render
  107.             self.content = self.rendered_content

File "/home/mythmon/src/normandy/recipe-server/.direnv/python-3.6.4/lib/python3.6/site-packages/rest_framework/response.py" in rendered_content
  72.         ret = renderer.render(self.data, accepted_media_type, context)

File "/home/mythmon/src/normandy/recipe-server/.direnv/python-3.6.4/lib/python3.6/site-packages/rest_framework/renderers.py" in render
  703.         context = self.get_context(data, accepted_media_type, renderer_context)

File "/home/mythmon/src/normandy/recipe-server/.direnv/python-3.6.4/lib/python3.6/site-packages/rest_framework/renderers.py" in get_context
  680.             'filter_form': self.get_filter_form(data, view, request),

File "/home/mythmon/src/normandy/recipe-server/.direnv/python-3.6.4/lib/python3.6/site-packages/rest_framework/renderers.py" in get_filter_form
  615.                 html = backend().to_html(request, queryset, view)

File "/home/mythmon/src/normandy/recipe-server/.direnv/python-3.6.4/lib/python3.6/site-packages/django_filters/rest_framework/backends.py" in to_html
  64.         template = loader.get_template(self.template)

File "/home/mythmon/src/normandy/recipe-server/.direnv/python-3.6.4/lib/python3.6/site-packages/django/template/loader.py" in get_template
  25.     raise TemplateDoesNotExist(template_name, chain=chain)

Exception Type: TemplateDoesNotExist at /api/v1/recipe/
Exception Value: django_filters/rest_framework/form.html
```

**Comment by mythmon** [comment]
It would be nice to add a test that would have caught this issue, though like I mentioned in my last comment, DRF doesn't seem to be cooperating on that front.

**Comment by peterbe** [comment]
I have to learn how django-rest-framework works first. 
This PR was ultimately started by the fact that those emails django being insecure were getting annoying. Perhaps can deal with that other untesting'ness in a separate issue.

**Comment by mythmon** [comment]
Looks like a transient error with apt-get in the last build failure. Lets try again:

bors r+

**Pull request merged**
