### PR TITLE
Don't require write permission to the main remote settings bucket

### LINKED ISSUE #1994: Remote settings exporter demands write access to main bucket, but it is not needed
The remote settings recipe exporter demands that it can write to the `normandy-recipes` collection on the `main` bucket. That isn't actually needed. We write the `main-workspace` bucket, and use Kinto's approval process to migrate changes to `main`. This was a regression introduced in #1960.

### PR DESCRIPTION
**Pull request by mythmon**
Fixes #1994

### CODE REVIEW

**Comment by jaredkerim** [comment]
@mythmon Ah looks like a test needs to be updated

**Comment by mythmon** [comment]
Oops. Lets try this.

**Pull request merged**
