### PR TITLE
Bug 1416003 - Handle preference studies on prefs with only user-branch values

### PR DESCRIPTION
**Pull request by mythmon**
This fixes a bug that I believe impacts 57. See the bug for more information.

### CODE REVIEW

**Comment by gijsk** [comment]
r=me with the nits from bugzilla. :-)

**Comment by mythmon** [comment]
I updated the patch to match the version that merged on Bugzilla. r?

**Comment by gijsk** [comment]
This is missing:

```
-const {utils: Cu} = Components;
+const {results: Cr, utils: Cu} = Components;
```

at the top of `bootstrap.js`.

**Comment by mythmon** [comment]
Oops. Fixed that.

**Pull request merged**
