### PR TITLE
1535 test coverage holes in api

### PR DESCRIPTION
**Pull request by peterbe**
To test this I ran:

```bash
pip install coverage
coverage run -m pytest normandy && coverage html --skip-covered
open htmlcov/index.html
```
I also had to create a `.coveragerc` which I don't know if we can add to the repo since we don't do coverage testing regularly. But I had to create this:

`.coveragerc`:
```
[run]
source = normandy
branch = True
data_file = /tmp/.coverage

[report]
omit =
    tests/*
    normandy/settings.py
    normandy/wsgi.py
    *management*
    *management/commands*

[xml]
output = /tmp/coverage.xml
```

### CODE REVIEW

**Comment by mythmon** [comment]
I think that adding the coverage file to the repository is a good idea. My opinions on test coverage have softened a bit lately. One question I have about that coverage file though, why exclude management commands? Especially because management commands are used as cron job entry points, they are an important part of our infrastructure that should probably have tests (at least some of them do already).

**Comment by peterbe** [comment]
> why exclude management commands

because I copied [the file from Tecken](https://github.com/mozilla-services/tecken/blob/master/.coveragerc) and just replaced the word "tecken" with "normandy". Kinda.

**Comment by peterbe** [comment]
> I think I'm just going to stop trying to merge things this week.

It's also 5pm my time so I'm in no rush. I'll do some retries on these next week.

**Comment by peterbe** [comment]
bors retry

**Pull request merged**
