### PR TITLE
Switch to Poetry

### LINKED ISSUE #2159: Switch to using Poetry
Pip, Hashin, `requirements/default.txt` and `requirements/constraints.txt` have served us well over the years, but they are missing a lot of modern niceties that newer approaches have. Lets try and use Poetry to manage Normandy's versions, which should be a little but nicer.

As a part of this we should make sure to update the onboarding docs, the Docker prod setup, the Docker dev setup, and CI.

### PR DESCRIPTION
**Pull request by mythmon**
Fixes #2159

### CODE REVIEW

**Comment by mythmon** [comment]
The main thing I was hoping you would check (and I should have said this earlier, sorry) was if the new docs worked for you locally. I tested out the Docker workflow a little, and CI works. I wanted to make sure the non-Docker dev environment worked for someone else too.

I'll fix the merge conflicts.

**Comment by tiftran** [comment]
ooohhh i ended up checking the docker workflow 😅

**Comment by tiftran** [comment]
kk i didn't seem to have any trouble for local dev

**Comment by mythmon** [comment]
Awesome, thanks for checking!

bors r= @tiftran

**Pull request merged**
