### PR TITLE
Recipe signing

### PR DESCRIPTION
**Pull request by mythmon**
* Adds signatures to Recipes
* Adds utilities to get signatures for byte strings
* Add management command to get signatures for Recipes
* Tweak test settings
* Change default DRF JSON renderer to output canonical JSON, so it can be hashed/signed

@Osmose r?

### CODE REVIEW

**Comment by mythmon** [comment]
I think I'm going to have to add something to this, so hold off on merging this for now.

**Comment by Osmose** [comment]
/me will wait for your addition to review

**Comment by mythmon** [comment]
Alright, I think that's all I'll need to add. The "x5u" field is used to validate the trust chain of the signature, which Firefox needs to validate the signature.

**Comment by mythmon** [comment]
Closing in favor of #190.

**Pull request closed without merging**
