### PR TITLE
Fix Karma failing on webpack

### PR DESCRIPTION
**Pull request by mythmon**
- [x] Make Karma fail if plugins can't be loaded
- [x] Fix webpack in the tests
- [x] Fix the failing test

### CODE REVIEW

**Comment by mythmon** [comment]
I'm not sure what's going on with that test. @Osmose, @rehandalal, do either of you have any ideas? I can't get the failure to happen locally.

**Comment by Osmose** [comment]
I got a lead!

I replicated the error by running the tests in a docker container like CI does, and eventually got the karma test runner open in Firefox and got both the actual exception and source code where it happened. Here's the bit that's failing:

```js
n=t.find("DisconnectedRecipeForm").get(0),n.changeAction({target:{value:"console-log"}})}),
```

So it's not finding the disconnected recipe form, which is raising an error when the temp variable it assigns it to is undefined.

**Comment by Osmose** [comment]
Changing the `webpack` key in `karma.conf.js` to this enables sourcemaps for all test runs, which changes the traceback to include the correct line (but not column) for errors:

```js
webpack: Object.assign(WEBPACK_CONFIG[0], {
  devtool: 'inline-source-map',
}),
```

**Comment by mythmon** [comment]
I haven't figured out how to fix the problem, but I've figured out how to reproduce it without Docker outside of CI. Unfortunately turning on `NODE_ENV=production` removes some of the helpful debugging from the tests, so it is hard to figure out what's going on.

With the changes I just pushed I get this sort of output locally, which is a lot easier to work with:

```
Firefox 52.0.0 (Linux 0.0.0): Executed 82 of 82 (1 FAILED) (1.479 secs / 1.414 secs)
TOTAL: 1 FAILED, 81 SUCCESS


1) should change the action in state & update the form
     <RecipeForm> changeAction
     Expected undefined to be defined.
@webpack:///client/control/tests/components/test_RecipeForm.js:43:6 <- client/control/tests/index.js:68:5934
patchFunction/obj[slot]/arguments[fnArgIndex]@node_modules/jasmine-promises/dist/jasmine-promises.js:35:23
patchFunction/obj[slot]/arguments[fnArgIndex]@node_modules/jasmine-promises/dist/jasmine-promises.js:47:11
patchFunction/obj[slot]/arguments[fnArgIndex]@node_modules/jasmine-promises/dist/jasmine-promises.js:47:11
patchFunction/obj[slot]/arguments[fnArgIndex]@node_modules/jasmine-promises/dist/jasmine-promises.js:47:11
patchFunction/obj[slot]/arguments[fnArgIndex]@node_modules/jasmine-promises/dist/jasmine-promises.js:47:11
patchFunction/obj[slot]/arguments[fnArgIndex]@node_modules/jasmine-promises/dist/jasmine-promises.js:47:11
     TypeError: n is undefined in client/control/tests/index.js (line 68)
@webpack:///client/control/tests/components/test_RecipeForm.js:44:6 <- client/control/tests/index.js:68:5958
patchFunction/obj[slot]/arguments[fnArgIndex]@node_modules/jasmine-promises/dist/jasmine-promises.js:35:23
patchFunction/obj[slot]/arguments[fnArgIndex]@node_modules/jasmine-promises/dist/jasmine-promises.js:47:11
patchFunction/obj[slot]/arguments[fnArgIndex]@node_modules/jasmine-promises/dist/jasmine-promises.js:47:11
patchFunction/obj[slot]/arguments[fnArgIndex]@node_modules/jasmine-promises/dist/jasmine-promises.js:47:11
patchFunction/obj[slot]/arguments[fnArgIndex]@node_modules/jasmine-promises/dist/jasmine-promises.js:47:11
patchFunction/obj[slot]/arguments[fnArgIndex]@node_modules/jasmine-promises/dist/jasmine-promises.js:47:11
     TypeError: n is undefined in client/control/tests/index.js (line 68)
@webpack:///client/control/tests/components/test_RecipeForm.js:48:6 <- client/control/tests/index.js:68:6075
patchFunction/obj[slot]/arguments[fnArgIndex]@node_modules/jasmine-promises/dist/jasmine-promises.js:35:23
patchFunction/obj[slot]/arguments[fnArgIndex]@node_modules/jasmine-promises/dist/jasmine-promises.js:47:11
patchFunction/obj[slot]/arguments[fnArgIndex]@node_modules/jasmine-promises/dist/jasmine-promises.js:47:11
patchFunction/obj[slot]/arguments[fnArgIndex]@node_modules/jasmine-promises/dist/jasmine-promises.js:47:11
patchFunction/obj[slot]/arguments[fnArgIndex]@node_modules/jasmine-promises/dist/jasmine-promises.js:47:11
patchFunction/obj[slot]/arguments[fnArgIndex]@node_modules/jasmine-promises/dist/jasmine-promises.js:47:11
```

**Comment by mythmon** [comment]
This is done and working now, including bringing it up to date with master.

**Pull request merged**
