### PR TITLE
yarn.lock changes after yarn install

### LINKED ISSUE #1763: yarn.lock changes after yarn install
git pulled `master` today and run `yarn` in it and that caused `yarn.lock` to change:

```diff
diff --git a/yarn.lock b/yarn.lock
index 37fe7d7d..315d0de2 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -648,11 +648,6 @@ ansi-escapes@^3.2.0:
   resolved "https://registry.yarnpkg.com/ansi-escapes/-/ansi-escapes-3.2.0.tgz#8780b98ff9dbf5638152d1f1fe5c1d7b4442976b"
   integrity sha512-cBhpre4ma+U0T1oM5fXg7Dy1Jw7zzwv7lt/GoCpr+hDQJoYnKVPLL4dCvSEFMmQurOQvSrwT7SL/DAlhBI97RQ==
 
-ansi-regex@^1.0.0:
-  version "1.1.1"
-  resolved "https://registry.yarnpkg.com/ansi-regex/-/ansi-regex-1.1.1.tgz#41c847194646375e6a1a5d10c3ca054ef9fc980d"
-  integrity sha1-QchHGUZGN15qGl0Qw8oFTvn8mA0=
-
 ansi-regex@^2.0.0:
   version "2.1.1"
   resolved "https://registry.yarnpkg.com/ansi-regex/-/ansi-regex-2.1.1.tgz#c3b33ab5ee360d86e0e628f0468ae7ef27d654df"
@@ -2035,7 +2030,7 @@ decode-uri-component@^0.2.0:
   resolved "https://registry.yarnpkg.com/decode-uri-component/-/decode-uri-component-0.2.0.tgz#eb3913333458775cb84cd1a1fae062106bb87545"
   integrity sha1-6zkTMzRYd1y4TNGh+uBiEGu4dUU=
 
-deep-extend@>=0.5.1, deep-extend@^0.4.1, deep-extend@^0.6.0:
+deep-extend@>=0.5.1, deep-extend@^0.6.0:
   version "0.6.0"
   resolved "https://registry.yarnpkg.com/deep-extend/-/deep-extend-0.6.0.tgz#c4fa7c95404a17a9c3e8ca7e1537312b736330ac"
   integrity sha512-LOHxIOaPYdHlJRtCQfDIVZtfw/ufM8+rVj649RIHzcm/vGwQRXFt6OPqIFWsm2XEMrNIEtWR64sY1LEKD2vAOA==
@@ -5314,13 +5309,6 @@ string_decoder@~1.0.3:
   dependencies:
     safe-buffer "~5.1.0"
 
-strip-ansi@^2.0.1:
-  version "2.0.1"
-  resolved "https://registry.yarnpkg.com/strip-ansi/-/strip-ansi-2.0.1.tgz#df62c1aa94ed2f114e1d0f21fd1d50482b79a60e"
-  integrity sha1-32LBqpTtLxFOHQ8h/R1QSCt5pg4=
-  dependencies:
-    ansi-regex "^1.0.0"
-
 strip-ansi@^3.0.0, strip-ansi@^3.0.1:
   version "3.0.1"
   resolved "https://registry.yarnpkg.com/strip-ansi/-/strip-ansi-3.0.1.tgz#6a385fb8853d952d5ff05d0e8aaf94278dc63dcf"
@@ -5698,15 +5686,6 @@ watchpack@^1.5.0:
     graceful-fs "^4.1.2"
     neo-async "^2.5.0"
 
-webpack-bundle-tracker@0.3.0:
-  version "0.3.0"
-  resolved "https://registry.yarnpkg.com/webpack-bundle-tracker/-/webpack-bundle-tracker-0.3.0.tgz#c900e9ecb54b639bec1b3bb8c0e9cd9400984c0c"
-  integrity sha512-I0Gwkug8QX8xZS14SvmfWin1AmZDoZp/0AGvlgKqNxyw20DgkFkq1jTQ/Ml73YgjFTmQ5bATyQM7TjtYMP1nFA==
-  dependencies:
-    deep-extend "^0.4.1"
-    mkdirp "^0.5.1"
-    strip-ansi "^2.0.1"
-
 webpack-cli@3.2.3:
   version "3.2.3"
   resolved "https://registry.yarnpkg.com/webpack-cli/-/webpack-cli-3.2.3.tgz#13653549adfd8ccd920ad7be1ef868bacc22e346"
```

Even weirder is that when I did a `rm -fr node_modules yarn.lock && yarn` it changed it even more compared to the `yarn.lock` in `master`.

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #1763

### CODE REVIEW

**Comment by peterbe** [comment]
So far, this PR just introduces a `yarn check` run in CI. I expect it to fail and once I update the `yarn.lock` it should succeed.

**Comment by peterbe** [comment]
Hmm... That didn't work. 

```
▶ yarn check
yarn check v1.13.0
warning "memory-fs#readable-stream@^2.0.1" could be deduped from "2.3.6" to "readable-stream@2.3.6"
warning "babel-eslint#@babel/traverse@^7.0.0" could be deduped from "7.2.3" to "@babel/traverse@7.2.3"
warning "eslint#ajv@^6.9.1" could be deduped from "6.9.2" to "ajv@6.9.2"
error "karma-webpack#webpack@^2.0.0 || ^3.0.0" doesn't satisfy found match of "webpack@4.29.5"
warning "webpack#ajv@^6.1.0" could be deduped from "6.9.2" to "ajv@6.9.2"
warning "webpack#node-libs-browser@^2.0.0" could be deduped from "2.1.0" to "node-libs-browser@2.1.0"
warning "@babel/core#@babel/helpers#@babel/traverse@^7.1.5" could be deduped from "7.2.3" to "@babel/traverse@7.2.3"
warning "@babel/core#@babel/template#@babel/parser@^7.2.2" could be deduped from "7.3.3" to "@babel/core#@babel/parser@7.3.3"
warning "@babel/core#@babel/template#@babel/types@^7.2.2" could be deduped from "7.3.3" to "@babel/core#@babel/types@7.3.3"
warning "babel-eslint#@babel/traverse#@babel/generator@^7.0.0" could be deduped from "7.2.2" to "@babel/generator@7.2.2"
warning "babel-eslint#@babel/traverse#@babel/helper-function-name@^7.0.0" could be deduped from "7.1.0" to "@babel/helper-function-name@7.1.0"
warning Resolution field "braces@2.3.2" is incompatible with requested version "karma#expand-braces#braces@^0.1.2"
warning "webpack#node-libs-browser#readable-stream@^2.0.5" could be deduped from "2.3.6" to "readable-stream@2.3.6"
warning "webpack#schema-utils#ajv@^6.1.0" could be deduped from "6.9.2" to "ajv@6.9.2"
warning "eslint#table#ajv@^6.9.1" could be deduped from "6.9.2" to "ajv@6.9.2"
warning "webpack#ajv-keywords#ajv@^6.0.0" could be deduped from "6.9.2" to "ajv@6.9.2"
warning "babel-eslint#@babel/traverse#@babel/helper-function-name#@babel/template@^7.0.0" could be deduped from "7.1.0" to "@babel/template@7.1.0"
warning "@babel/helpers#@babel/template#@babel/types@^7.1.2" could be deduped from "7.2.0" to "@babel/helpers#@babel/types@7.2.0"
warning "@babel/helpers#@babel/traverse#@babel/generator@^7.1.5" could be deduped from "7.2.2" to "@babel/generator@7.2.2"
warning "@babel/helpers#@babel/traverse#@babel/types@^7.1.5" could be deduped from "7.2.0" to "@babel/helpers#@babel/types@7.2.0"
warning "terser-webpack-plugin#cacache#lru-cache@^4.1.3" could be deduped from "4.1.5" to "lru-cache@4.1.5"
warning "chokidar#fsevents#node-pre-gyp@^0.10.0" could be deduped from "0.10.3" to "node-pre-gyp@0.10.3"
warning "chokidar#readdirp#readable-stream@^2.0.2" could be deduped from "2.3.6" to "readable-stream@2.3.6"
warning "node-libs-browser#stream-browserify#readable-stream@^2.0.2" could be deduped from "2.3.6" to "readable-stream@2.3.6"
warning "webpack#node-libs-browser#stream-http#readable-stream@^2.2.6" could be deduped from "2.3.6" to "readable-stream@2.3.6"
warning "schema-utils#ajv-errors#ajv@>=5.0.0" could be deduped from "6.9.2" to "ajv@6.9.2"
warning "schema-utils#ajv-keywords#ajv@^6.0.0" could be deduped from "6.9.2" to "ajv@6.9.2"
warning "@babel/helpers#@babel/traverse#@babel/generator#@babel/types@^7.1.5" could be deduped from "7.2.0" to "@babel/helpers#@babel/types@7.2.0"
warning "npmlog#are-we-there-yet#readable-stream@^2.0.6" could be deduped from "2.3.6" to "readable-stream@2.3.6"
info Found 28 warnings.
error Found 1 errors.
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
```

Note, prior to running this I ran `yarn` which changed `yarn.lock`. Now every time I run `yarn` it no longer changes `yarn.lock`. 

I think I jumped to conclusions about how `yarn check` works.

**Comment by peterbe** [comment]
@mythmon or @rehandalal, any idea for some better ways to do this? 

Essentially, `yarn check` does something else. It doesn't check if the `yarn.lock` is going to have to change. 
`yarn install --frozen-lockfile` will throw an error if something needs to be updated but it doesn't do a sync like that. If you run `yarn install --frozen-lockfile` today on normandy `master` it will *not* update the `yarn.lock` file. 

The only way I can think of is to run...:

```
$ cp yarn.lock yarn.lock.before
$ yarn install
$ diff yarn.lock yarn.lock.before
$ echo $?
```

**Comment by mythmon** [comment]
I think running yarn install and checking if `yarn.lock` changed makes sense. I'd do it with git though

```
yarn install
if git ls-files --modified --error-unmatch package.json; then
  echo "The file changed"
else
  echo "The file did not change"
fi

[python-3.7.1] ~/src/normandy · (unpin±)
⟩

**Comment by peterbe** [comment]
So this is the bug: https://github.com/yarnpkg/yarn/issues/5840

In particular, see the latest comment about using `git diff` to check manually: https://github.com/yarnpkg/yarn/issues/5840#issuecomment-467516207
I still don't like that feature because I'm not sure how to run that with `docker-compose` and if it means it has to be run outside the scope of the `Dockerfile`, does that mean it needs to run the whole node_modules download thing for every single PR?

I'm tempted, unless you total object, that we manually patch `yarn.lock` for now and keep a keen eye on movement on that issue for a day when `yarn install --frozen-lockfile` (or some other "native" yarn command) will **fail** if a package has been removed from `package.json` but not synced with `yarn.lock`.

**Comment by mythmon** [comment]
> I'm tempted, unless you total object, that we manually patch `yarn.lock` for now and keep a keen eye on movement on that issue for a day when `yarn install --frozen-lockfile` (or some other "native" yarn command) will **fail** if a package has been removed from `package.json` but not synced with `yarn.lock`.

I think this is a good way forward at this point. This proved more complicated than I expected (I had hoped `yarn check` was the thing we needed). Since this doesn't affect our prod or CI builds, and when it does it will fail loudly, I'm ok leaving it in place.

**Comment by peterbe** [comment]
> I'm ok leaving it in place.

uh. Now I'm confused. Leave what in place?

What I'm proposing is that I close this PR (or start over) and just patch only the `yarn.lock`. We can revisit adding a step in `.circleci/config.yml` later when `yarn` becomes awesomer.

**Comment by mythmon** [comment]
Oops. I mean to say "I'm ok leaving *this* in place", as in, leaving things the way they are. That wasn't very clear of me though, sorry.

I agree with just patching `yarn.lock` to make the immediate issue go away.

**Comment by peterbe** [comment]
Another horrible solution is to look at the total diff and if `package.json` is in the diff but `yarn.lock` is *not* is that you could study the diff in `package.json` and see if what is changed is anything within the `dependencies` or `devDependencies` keys. Nuts!

**Comment by peterbe** [comment]
Lemme know if you want me to squash this. 

I only hope that we remember to keep an eye on `yarn` to solve this "natively" so once there we can start using that in CI.

**Comment by peterbe** [comment]
bors r= @mythmon

**Pull request merged**
