### PR TITLE
Fix #1176 - Remove recipe-client-addon

### LINKED ISSUE #1176: Remove recipe-client-addon
The recipe-client-addon is moving its canonical sources to mozilla-central. This will help ease the add-on's deployment workflow (no more syncing changes back and forth), and will enable the Normandy client to eventually become a Firefox feature instead of a system add-on.

This covers

* [x] Remove the recipe-client-addon directory
* [x] Remove Taskcluster CI
* [x] Make Github and Bors allow PRs to merge without Taskcluster CI
* [x] Move any relevant documentation to [firefox-source-docs](https://firefox-source-docs.mozilla.org/) ([Bug 1435350](https://bugzilla.mozilla.org/show_bug.cgi?id=1435350))

### PR DESCRIPTION
**Pull request by mythmon**
The recipe-client-addon's canonical location is now in mozilla-central, at https://hg.mozilla.org/mozilla-central/file/tip/browser/extensions/shield-recipe-client

🔴 🔴 🔴

### CODE REVIEW

**Comment by mostlygeek** [comment]
Shouldn't it be named "normandy-recipe-client" in mozilla-central?

**Comment by mythmon** [comment]
> Shouldn't it be named "normandy-recipe-client" in mozilla-central?

This PR only covers the removal of the code from this repo. The renaming and reorganizing of the code in mozilla-central is a separate concern. It has been in the tree for over a year by the name "shield-recipe-client". I'd prefer to make one large change instead of many small confusing changes.

**Comment by mythmon** [comment]
You read my mind. We *are* planning on moving to a component instead of a system add-on. Like you said, that isn't a part of this PR though.

bors r= @gijsk, @rehandalal

**Comment by mostlygeek** [comment]
> This PR only covers the removal of the code from this repo. The renaming and reorganizing of the code in mozilla-central is a separate concern. It has been in the tree for over a year by the name "shield-recipe-client". I don't want to rename it just now.

Is there a bug for it that I can follow?

**Pull request merged**
