### PR TITLE
Reuse server image  in docker-compose in CI

### PR DESCRIPTION
**Pull request by mythmon**
Hopefully this fixes some of the problems in #439.

### CODE REVIEW

**Comment by mythmon** [comment]
@Osmose I think compose  is using the right images now, but something is going wrong with the recipe server ci. can you look at it?

**Comment by Osmose** [comment]
Hmmm. I _was_ getting the error locally, but the last commit fixes it for me. Yet CI is still having issues.

We might have to make a wait-for-postgres script or something.

**Comment by Osmose** [comment]
Permission denied! We're past the postgres hump, with the setup I've been most happy with over all the variations of things I've tried. This is back to erroring out at writing the product_details JSON to the filesystem.

**Comment by rehandalal** [comment]
I've tried switching from `PDFileStorage` to `PDDatabaseStorage` but can't get that to work.

I keep getting:
```
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by Osmose** [comment]
Weird, what's the traceback on that? Are we importing from django too early somewhere?

**Comment by mythmon** [comment]
As for as the permission denied problems, running as the root user instead of the default app user usually fixes that. I'm not sure how to do that with docker-compose though.

**Comment by rehandalal** [comment]
The product details issue should be fixed. The latest version of product details has a bug that was causing the issues with `PDDatabaseStorage` so I rolled back the version. I tried to fix the subsequent issues with mock-recipe-server but I think someone else should probably look at that.

**Comment by mythmon** [comment]
Closing in favor of #434, since we dropped mock-recipe-client in #447.

**Pull request closed without merging**
