### PR TITLE
add /__lbheartbeat__ so the elb can see the application is responsive

### PR DESCRIPTION
**Pull request by relud**
not sure if it should return `Response('', status=status.HTTP_200_OK)` or just `Response('')` or something else. Expected behavior is to return 200 with an empty body.

### CODE REVIEW

**Comment by mythmon** [comment]
200 is the default return code, so it is redundant right now, but this is fine.

PS: Technically [`HTTP 204 No Content`](http://http.cat/204) would be semantically better, but I imagine the load balancers don't like that?

**Comment by relud** [comment]
pretty sure any 2xx would be fine.

**Comment by relud** [comment]
I was wrong, docs say it must be 200 :/

**Comment by mythmon** [comment]
r+

**Pull request merged**
