### PR TITLE
#785: Remove approval comment from popover

### LINKED ISSUE #785: the approval block elem needs overflow control
using `pre` here by default won't wrap the text, gets a bit hairy, and possibly might break in awkward ways in other circumstances. Should a `div` work fine in this instance?

screen shot 2017-05-25 at 4 12 32 pm

### PR DESCRIPTION
**Pull request by andymikulski**
Fixes #785 (more accurately, finishes #785)

- #785 called for fixing a UI element that no longer exists in the new UI
- While checking to confirm #785 had been met, I found that using the approval comments as tooltips in the HistoryTimeline lead to a real wide string across the page:
screen shot 2017-08-07 at 1 13 08 pm

- This PR removes the comment from the tooltip, since the full text comment is available on the approval history page: 
screen shot 2017-08-07 at 12 47 28 pm

- Also noticed that the `Responsed` field on approval requests did not reflect useful information, so it was removed.

R?

### CODE REVIEW

**Comment by mythmon** [comment]
@rehandalal want to take this one?

**Comment by mythmon** [comment]
@gregglind can you leave a review about the UI change here? We can handle reviewing the code changes.

**Comment by andymikulski** [comment]
I've spoken with @rehandalal on this, and we're going to modify the CSS a bit to keep the pop-over approval comment in place.

**Comment by andymikulski** [comment]
I've changed this PR to only affect the placement + style of the popover:

screen shot 2017-08-24 at 10 55 43 am

This is ready for re-review!

**Comment by andymikulski** [comment]
Yeah, I noticed that too, thought it was weird. I should have just changed it then. I'll correct that and then merge this branch!

**Comment by andymikulski** [comment]
screen shot 2017-08-29 at 11 00 11 am

I've switched the popover BG back to white, right-justified the author name, and switched some punctuation around. Let me know if you feel strongly opposed to this @rehandalal .

**Pull request merged**
