### PR TITLE
Fix high population switch not saving.

### PR DESCRIPTION
**Pull request by mythmon**
The Python tests are a sanity check that nothing is going wrong in the API. The changes in the JS should be better form code that doesn't accidentally throw away data.

@rehandalal r?

### CODE REVIEW

**Comment by notriddle** [comment]
error: could not rename component directory from '/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/etc' to '/root/.rustup/tmp/hndv_r6y7cutu54x_dir/bk'

wat 🦆

**Comment by mythmon** [comment]
@notriddle this is a problem we see commonly in our CI. It is something that would be a good match for bors-ng/bors-ng#157. We do full builds of Firefox, which rely on keeping an up-to-date version of Rust. Our build image is static, so about every 6 weeks we have to kick it to update Rust.

There may be a better solution to this, in the form of figuring out why rustup can't update itself, but I haven't looked into it yet.

**Comment by mythmon** [comment]
bors r= @rehandalal

**Comment by mythmon** [comment]
@rdalal The only failure was a simple lint problem. re-r?

**Comment by rehandalal** [comment]
haz moar problems!

**Comment by mythmon** [comment]
bors r= @rehandalal

**Pull request merged**
