### PR TITLE
Cancel the monorepo, and make recipe-server the sole project

### LINKED ISSUE #1188: Remove the CI infrastructure made for the monorepo.
Currently we have a complicated CI infrastructure for running various steps in multiple projects. With the monorepo being broken up, this is no longer needed. It is causing complexity in CI, linting, and preventing us from using pre-commit hooks. We should get rid of it.

### LINKED ISSUE #1200: Delete code for updating the mock server
The mock server has outlived its usefulness. QA is generally done by making recipes directly on the staging server, and the breadth of needed recipes is larger than the mock server is going to be able to support.

### PR DESCRIPTION
**Pull request by mythmon**
The monorepo is so 2017. It's 2018 now, and single-purpose repos are the new hotness.

* Remove some stray files belonging to recipe-client-addon. It has been migration to mozilla-central
* Remove mock-recipe-server. QA mostly uses the stage deployment directly instead.
* Remove functional_tests. They have been disabled for a long time (#644).
* Remove e2e-tests. They are only applicable to the UI, and were never enabled in CI (#1021).
* Remove monorepo CI infrastructure.
* Update docs to account for the above

Fixes #1188 
Fixes #1200

### CODE REVIEW

**Comment by mostlygeek** [comment]
Does this remote normandy-admin? 

We should support normandy-admin until Delivery Console is ready for production.

**Comment by mythmon** [comment]
This does not remove the normandy admin, because historically it was part of the recipe-server instead of a separate project.

**Comment by mostlygeek** [comment]
Does this just remove the recipe-client?

**Comment by mythmon** [comment]
This PR removes recipe-client-addon, mock-recipe-server, functional_tests, and e2e-tests. It also changes CI  to account for the above and simplifies CI slightly. I still need to update the docs and get CI working. I didn't, but should have, tagged this as WIP. It is mostly open to get CI's opinion. That's why I assigned it to myself and didn't ask for review yet.

**Comment by rehandalal** [comment]
Sorry! I come bearing more merge conflicts!

**Comment by mythmon** [comment]
Rebased on master to fix merge conflicts. Quick, lets land it before it breaks again

**Pull request merged**
