### PR TITLE
Build docs with Python 3.6 on ReadTheDocs

### PR DESCRIPTION
**Pull request by mythmon**
In #1352, I was trying to accommodate RTD using Python 3.5 to build our docs. I was able to eventually get all the packages to install, but then ran into another issue: Our code is not compatible with Python 3.5. Mostly because we use f-strings. This isn't something I could change with requirements files.

Fortunately, it is [now possible to get RTD to use Python 3.6](http://docs.readthedocs.io/en/latest/yaml-config.html#build-image). So I did that instead.

I've tested this commit, and it [actually builds](https://readthedocs.org/projects/normandy/builds/7171416/) on RTD, so this should be the last one.

### CODE REVIEW

**Comment by rehandalal** [comment]
oh fuck! missed the merge conflicts 😢

**Comment by mythmon** [comment]
Oh well, not your fault. Bors will catch us.

**Comment by mythmon** [comment]
I fixed the merge conflict.

bors r= @rehandalal

**Comment by mythmon** [comment]
[It worked!](https://readthedocs.org/projects/normandy/builds/7171610/)

**Pull request merged**
