### PR TITLE
Dependencies 2021 Q2

### PR DESCRIPTION
**Pull request by mythmon**

### CODE REVIEW

**Comment by mythmon** [comment]
@jrconlin, I can't request it through the Github tool, but can you review this? If you are happy with it, you can approve and merge it by saying `bors merge` in its own Markdown paragraph.

bors delegate= @jrconlin

**Review by jrconlin — APPROVED** [review]

**Comment by jrconlin** [comment]
bors merge

**Review by jrconlin — APPROVED** [review]
bors merge

**Comment by mythmon** [comment]
It seems like bors had a hiccup yesterday. #2319 didn't trigger either. Lets try again.

bors r= @jrconlin

**Pull request merged**
